name: TWS CI Workflow

on :
  push:
  
jobs: 
  build: #job ka naam
    runs-on: ubuntu-latest #GitHub runner (free)
    steps: 
      -name: checkout code
       uses: actions/checkout #clone the code into a ubuntu runner

      -name: Setup docker
       uses: docker/setup-buildx-action@v4
  
